name: Seed Database and Push Changes

on:
  schedule:
    - cron: '30 11 * * *'  # Runs at 11:30 UTC daily
  workflow_dispatch:

jobs:
  seed_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use the appropriate Node.js version

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Start Next.js app in the background
        run: npm run build && npm run start &

      - name: Wait for the server to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:3000/api/repos && break
            echo "Waiting for server to be ready..."
            sleep 5
          done

      - name: Send request to /api/seed
        run: |
          curl http://localhost:3000/api/seed

      - name: Check for changes in SQLite DB
        env:
          GH_PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "feat: new entities added"
            git push "https://${GH_PAT}@github.com/onurkanbakirci/trendsgit.git" HEAD:main
          else
            echo "No changes to commit."
          fi

                - name: Commit and push changes if any